name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: build test
      run: |  
          mkdir build && cd build
          cmake ..
          make
          echo "All is OK. Build verified."
    - name: test
      run: |  
          cd build
          ./main
          echo "Test runed."
    
